A couple of improvements for the stricter rule
ykoksen/unused-task-warning pull request #16
Opened 2019-04-17 08:53 UTC by samusaran

I've modified a couple of things:
- Since my stricter check would only be relevant in cases where the callee is an async method, I've added that condition, intended to limit the "noise" of that check.
- I've added a more clear warning message for the new check, which specifies that the behaviour could be the expected one.

Let me know what you think!

2019-04-17 16:44 UTC, ykoksen commented
I don't have time to make a full review now as I'm going on Easter vacation, but I'll look into it when I get back.

2019-04-17 16:49 UTC, ykoksen commented on Lindhart.Analyser.MissingAwaitWarning/Lindhart.Analyser.MissingAwaitWarning/Lindhart.Analyser.MissingAwaitWarning/LindhartAnalyserMissingAwaitWarningAnalyzer.cs
> +                            if (EqualsType(methodSymbol.ReturnType, syntaxNodeAnalysisContext.SemanticModel, AwaitableTypes) && methodSymbol.IsAsync)
If the method you are calling is on an interface you don't know if the implementation is `async`. Also on a class you could have a method which is not `async`, which returns a `Task`, which should be awaited in a normal flow.

2019-04-17 16:52 UTC, ykoksen requested changes

2019-04-17 16:52 UTC, ykoksen commented on Lindhart.Analyser.MissingAwaitWarning/Lindhart.Analyser.MissingAwaitWarning/Lindhart.Analyser.MissingAwaitWarning/Resources.resx
> +    <value>The async method '{0}' returns a Task that is not awaited. This could be the expected behaviour, depending of your context.</value>
We don't investigate if this `Task` is not awaited. We only investigate if it is awaited on the current line. I believe this should be explicit in the message. The `Task` can very well be awaited on another line (the most used use-case I've seen for assigning the `Task` to a variable).

2019-06-07 09:36 UTC, samusaran commented
I'm closing this pull request since all the changes are included in the other branch I'm working on.

2019-06-07 09:36 UTC, closed without merging