Prevent NRE on type symbols without namespace
ykoksen/unused-task-warning pull request #6
Opened 2018-03-13 18:56 UTC by MaxHorstmann

Analyser throws NullReferenceException on symbols without namespace; this fixes it.

2018-05-24 20:45 UTC, ykoksen requested changes
Looks really good. However I would like a unit test that tests the scenario. I tried to make one but it doesn't seem trivial. I might try later.

2018-08-10 19:55 UTC, ykoksen commented
Tried long and hard to make a unit test that throws the `NullReferenceException` - but it seems impossible. Classes that are declared without a namespace automatically gets the global namespace. I believe it is simply impossible to get this exception with this analyser (please prove me wrong) since the `ISymbol` will always be a type. 

However I do also recognise that I'm using a property that states that it in some cases can return null (ex. when the symbol is a namespace) - and as such this should be checked (checking for `null`). I will therefore accept this merge request.

2018-08-10 19:55 UTC, ykoksen approved these changes

2018-08-10 19:56 UTC, merged

2018-08-13 15:53 UTC, MaxHorstmann commented
@ykoksen thanks for merging this! Sorry, I must have missed your message in May about a unit test. I'll check if I can still repro the original issue and will add a unit test for it if I can.